/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelDolar extends javax.swing.JPanel {

    /**
     * Creates new form JpanelDolar
     */
    public JpanelDolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecioDolar = new javax.swing.JLabel();
        txtInputDolar = new javax.swing.JTextField();
        btnConversorDolar = new javax.swing.JButton();
        lblCantidadDolar = new javax.swing.JLabel();
        lblSignoDolar = new javax.swing.JLabel();
        lblSignoCLP = new javax.swing.JLabel();
        BtnInvertir = new javax.swing.JButton();
        lblSimboloMonetarioDolar = new javax.swing.JLabel();

        lblPrecioDolar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioDolar.setForeground(new java.awt.Color(255, 0, 51));
        lblPrecioDolar.setText("0.0013");

        btnConversorDolar.setText("Convertir");
        btnConversorDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversorDolarActionPerformed(evt);
            }
        });

        lblCantidadDolar.setEnabled(false);

        lblSignoDolar.setText("USD");
        lblSignoDolar.setEnabled(false);

        lblSignoCLP.setText("CLP $");

        BtnInvertir.setText("Invertir");
        BtnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvertirActionPerformed(evt);
            }
        });

        lblSimboloMonetarioDolar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSimboloMonetarioDolar.setForeground(new java.awt.Color(255, 0, 51));
        lblSimboloMonetarioDolar.setText("US$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSignoDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadDolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(BtnInvertir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSimboloMonetarioDolar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecioDolar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSignoCLP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnConversorDolar)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSimboloMonetarioDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnInvertir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInputDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnConversorDolar)
                                .addComponent(lblSignoCLP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSignoDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConversorDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorDolarActionPerformed
        try {
            Double valor;
            DecimalFormat decimales = new DecimalFormat("#.##");
            valor = Double.parseDouble(txtInputDolar.getText())* Double.parseDouble(lblPrecioDolar.getText());
            lblCantidadDolar.setText(decimales.format(valor));
        } catch (NumberFormatException | ArithmeticException exception) {
            lblCantidadDolar.setText("Valor mal ingresado");
        }       
    }//GEN-LAST:event_btnConversorDolarActionPerformed

    private void BtnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvertirActionPerformed
        // TODO add your handling code here:
        
        try {
            if("CLP $".equals(lblSimboloMonetarioDolar.getText())){
                lblSimboloMonetarioDolar.setText("US$");
                lblPrecioDolar.setText("0.0013");
                lblSignoDolar.setText("USD");
                lblSignoCLP.setText("CLP $");
                lblCantidadDolar.setText("");
                txtInputDolar.setText("");
            }else{
                lblSimboloMonetarioDolar.setText("CLP $");
                lblPrecioDolar.setText("794.89");
                lblSignoDolar.setText("$");
                lblSignoCLP.setText("USD");
                lblCantidadDolar.setText("");
                txtInputDolar.setText("");
            }
            
        } catch (Exception e) {
            System.out.println("Hubo un problema al invertir "+e);
        }
    }//GEN-LAST:event_BtnInvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInvertir;
    private javax.swing.JButton btnConversorDolar;
    private javax.swing.JLabel lblCantidadDolar;
    private javax.swing.JLabel lblPrecioDolar;
    private javax.swing.JLabel lblSignoCLP;
    private javax.swing.JLabel lblSignoDolar;
    private javax.swing.JLabel lblSimboloMonetarioDolar;
    private javax.swing.JTextField txtInputDolar;
    // End of variables declaration//GEN-END:variables
}
