/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelPesoChe extends javax.swing.JPanel {

    /**
     * Creates new form JpanelDolar
     */
    public JpanelPesoChe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecioPesoArgentino = new javax.swing.JLabel();
        txtInputPesoArgentino = new javax.swing.JTextField();
        btnConversorPesoArgentino = new javax.swing.JButton();
        lblCantidadPesoArgentino = new javax.swing.JLabel();
        lblSignoPesoArgentino = new javax.swing.JLabel();
        lblSignoCLP = new javax.swing.JLabel();
        BtnInvertir = new javax.swing.JButton();
        lblSimboloPesoArgentino = new javax.swing.JLabel();

        lblPrecioPesoArgentino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioPesoArgentino.setForeground(new java.awt.Color(255, 0, 51));
        lblPrecioPesoArgentino.setText("0.26");

        btnConversorPesoArgentino.setText("Convertir");
        btnConversorPesoArgentino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversorPesoArgentinoActionPerformed(evt);
            }
        });

        lblCantidadPesoArgentino.setEnabled(false);

        lblSignoPesoArgentino.setText("ARG $");
        lblSignoPesoArgentino.setEnabled(false);

        lblSignoCLP.setText("$");

        BtnInvertir.setText("Invertir");
        BtnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvertirActionPerformed(evt);
            }
        });

        lblSimboloPesoArgentino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSimboloPesoArgentino.setForeground(new java.awt.Color(255, 0, 51));
        lblSimboloPesoArgentino.setText("ARG $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSignoPesoArgentino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(lblSimboloPesoArgentino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioPesoArgentino))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSignoCLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInputPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnInvertir)
                    .addComponent(btnConversorPesoArgentino))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSimboloPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnInvertir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInputPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnConversorPesoArgentino)
                                .addComponent(lblSignoCLP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSignoPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadPesoArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConversorPesoArgentinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorPesoArgentinoActionPerformed
        // TODO add your handling code here:
        try { 
            Double valor;  
            DecimalFormat decimales = new DecimalFormat("#.####");
            valor = Double.parseDouble(txtInputPesoArgentino.getText())* Double.parseDouble(lblPrecioPesoArgentino.getText());
            lblCantidadPesoArgentino.setText(decimales.format(valor));
        } catch (NumberFormatException | ArithmeticException exception) {
            lblCantidadPesoArgentino.setText("Valor mal ingresado"+exception); 
        }   
    }//GEN-LAST:event_btnConversorPesoArgentinoActionPerformed

    private void BtnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvertirActionPerformed
        // TODO add your handling code here:
        try {
            if("CLP $".equals(lblSimboloPesoArgentino.getText())){
                lblSignoCLP.setText("CLP $");
                lblSignoPesoArgentino.setText("ARG $");
                lblSimboloPesoArgentino.setText("ARG $");
                lblCantidadPesoArgentino.setText("");
                lblPrecioPesoArgentino.setText("3.83");
                txtInputPesoArgentino.setText(""); 
            }else{
                lblSignoPesoArgentino.setText("CLP $");
                lblSignoCLP.setText("ARG $");
                lblSimboloPesoArgentino.setText("CLP $");
                lblCantidadPesoArgentino.setText("");
                lblPrecioPesoArgentino.setText("0.26");
                txtInputPesoArgentino.setText("");
            }
            
        } catch (Exception e) {
            System.out.println("Hubo un problema al invertir "+e);
        }
        
        
    }//GEN-LAST:event_BtnInvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInvertir;
    private javax.swing.JButton btnConversorPesoArgentino;
    private javax.swing.JLabel lblCantidadPesoArgentino;
    private javax.swing.JLabel lblPrecioPesoArgentino;
    private javax.swing.JLabel lblSignoCLP;
    private javax.swing.JLabel lblSignoPesoArgentino;
    private javax.swing.JLabel lblSimboloPesoArgentino;
    private javax.swing.JTextField txtInputPesoArgentino;
    // End of variables declaration//GEN-END:variables
}
