/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelEuro extends javax.swing.JPanel {

    /**
     * Creates new form JpanelDolar
     */
    public JpanelEuro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecioEuro = new javax.swing.JLabel();
        txtInputEuro = new javax.swing.JTextField();
        btnConversorEuro = new javax.swing.JButton();
        lblCantidadEuro = new javax.swing.JLabel();
        lblSignoEuro = new javax.swing.JLabel();
        lblSignoCLP = new javax.swing.JLabel();
        btnInvertir = new javax.swing.JButton();
        lblSimboloMonetarioEuro = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 200));

        lblPrecioEuro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioEuro.setForeground(new java.awt.Color(255, 0, 51));
        lblPrecioEuro.setText("0.0012");

        btnConversorEuro.setText("Convertir");
        btnConversorEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversorEuroActionPerformed(evt);
            }
        });

        lblCantidadEuro.setEnabled(false);

        lblSignoEuro.setText("€ ");
        lblSignoEuro.setEnabled(false);

        lblSignoCLP.setText("CLP $");

        btnInvertir.setText("Invertir");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });

        lblSimboloMonetarioEuro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSimboloMonetarioEuro.setForeground(new java.awt.Color(255, 0, 51));
        lblSimboloMonetarioEuro.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblSignoEuro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadEuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addComponent(btnInvertir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSimboloMonetarioEuro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioEuro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSignoCLP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnConversorEuro)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSimboloMonetarioEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInvertir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInputEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnConversorEuro)
                                .addComponent(lblSignoCLP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSignoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConversorEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorEuroActionPerformed
        // TODO add your handling code here:
        try {
            Double valor;
            DecimalFormat decimales = new DecimalFormat("#.##");
            valor = Double.parseDouble(txtInputEuro.getText())* Double.parseDouble(lblPrecioEuro.getText());
            lblCantidadEuro.setText(decimales.format(valor));
        } catch (NumberFormatException | ArithmeticException exception) {
            lblCantidadEuro.setText("Valor mal ingresado");
        }     
        
    }//GEN-LAST:event_btnConversorEuroActionPerformed

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
        // TODO add your handling code here:
         try {
            if("CLP $".equals(lblSimboloMonetarioEuro.getText())){
                lblSignoCLP.setText("CLP $");
                lblSignoEuro.setText("€");
                lblSimboloMonetarioEuro.setText("€");
                lblCantidadEuro.setText("");
                lblPrecioEuro.setText("0.0012");
                txtInputEuro.setText(""); 
            }else{
                lblSignoEuro.setText("CLP $");
                lblSignoCLP.setText("€");
                lblSimboloMonetarioEuro.setText("CLP $");
                lblCantidadEuro.setText("");
                lblPrecioEuro.setText("857.98");
                txtInputEuro.setText("");
            }
            
        } catch (Exception e) {
            System.out.println("Hubo un problema al invertir "+e);
        }
    }//GEN-LAST:event_btnInvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConversorEuro;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JLabel lblCantidadEuro;
    private javax.swing.JLabel lblPrecioEuro;
    private javax.swing.JLabel lblSignoCLP;
    private javax.swing.JLabel lblSignoEuro;
    private javax.swing.JLabel lblSimboloMonetarioEuro;
    private javax.swing.JTextField txtInputEuro;
    // End of variables declaration//GEN-END:variables
}
