/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelGramos extends javax.swing.JPanel {

    /**
     * Creates new form JpanelPies
     */
    public JpanelGramos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignoGrs = new javax.swing.JLabel();
        txtInputGramos = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        lblOnzas = new javax.swing.JLabel();
        lblKilos = new javax.swing.JLabel();
        lbLibras = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSignoOz = new javax.swing.JLabel();
        lblSignoKg = new javax.swing.JLabel();
        lblSignoLb = new javax.swing.JLabel();

        lblSignoGrs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoGrs.setText("Grs.");

        txtInputGramos.setText(" ");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        lblOnzas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOnzas.setText(" ");

        lblKilos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKilos.setText(" ");

        lbLibras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLibras.setText(" ");

        lblTitulo.setText("Gramos a Kilos");

        lblSignoOz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoOz.setText("Oz");
        lblSignoOz.setEnabled(false);

        lblSignoKg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoKg.setText("Kg");
        lblSignoKg.setEnabled(false);

        lblSignoLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoLb.setText("Lb");
        lblSignoLb.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoGrs)
                    .addComponent(lblSignoOz)
                    .addComponent(lblSignoKg)
                    .addComponent(lblSignoLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbLibras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKilos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOnzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInputGramos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConvertir))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir)
                    .addComponent(lblSignoGrs))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnzas)
                    .addComponent(lblSignoOz))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblSignoKg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKilos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLibras)
                    .addComponent(lblSignoLb))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        //Constantes
        double onzas = 0.035274;
        double kilos = 0.001;
        double libras = 0.00220462;
        
        double metricaOnzas;
        double metricaKilos;
        double metricaLibras;
        
        lblSignoKg.setEnabled(true);
        lblSignoLb.setEnabled(true);
        lblSignoOz.setEnabled(true);

        try {
            if (txtInputGramos.getText().length()>0) {
                DecimalFormat decimales = new DecimalFormat("#.##");
                metricaOnzas = Double.parseDouble(txtInputGramos.getText())*onzas;
                metricaKilos = Double.parseDouble(txtInputGramos.getText())*kilos;
                metricaLibras = Double.parseDouble(txtInputGramos.getText())*libras;

                lblKilos.setText(decimales.format(metricaKilos));
                lblOnzas.setText(decimales.format(metricaOnzas));
                lbLibras.setText(decimales.format(metricaLibras));
            }else{
                lblKilos.setText("Numero error");
                lblOnzas.setText("Numero error");
                lbLibras.setText("Numero error");
            }

        } catch (Exception e) {
            lblKilos.setText("Ingrese un número");
            lblOnzas.setText("Ingrese un número");
            lbLibras.setText("Ingrese un número");
            System.out.println("Hubo un error "+e);
        }   
    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel lbLibras;
    private javax.swing.JLabel lblKilos;
    private javax.swing.JLabel lblOnzas;
    private javax.swing.JLabel lblSignoGrs;
    private javax.swing.JLabel lblSignoKg;
    private javax.swing.JLabel lblSignoLb;
    private javax.swing.JLabel lblSignoOz;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtInputGramos;
    // End of variables declaration//GEN-END:variables
}
