/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelPies extends javax.swing.JPanel {

    /**
     * Creates new form JpanelPies
     */
    public JpanelPies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignoFt = new javax.swing.JLabel();
        txtInputPies = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        lblCm = new javax.swing.JLabel();
        lblMts = new javax.swing.JLabel();
        lblIn = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSignoMts = new javax.swing.JLabel();
        lblSignoIn = new javax.swing.JLabel();
        lblSignoCm = new javax.swing.JLabel();

        lblSignoFt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoFt.setText("ft");

        txtInputPies.setText(" ");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        lblCm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCm.setText(" ");

        lblMts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMts.setText(" ");

        lblIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIn.setText(" ");

        lblTitulo.setText("Pies a Cm - Mts - In");

        lblSignoMts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoMts.setText("Mts");
        lblSignoMts.setEnabled(false);

        lblSignoIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoIn.setText("In");
        lblSignoIn.setEnabled(false);

        lblSignoCm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoCm.setText("Cm");
        lblSignoCm.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignoFt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoMts, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoCm, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInputPies, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConvertir))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputPies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir)
                    .addComponent(lblSignoFt))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCm)
                    .addComponent(lblSignoCm))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMts)
                    .addComponent(lblSignoMts))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIn)
                    .addComponent(lblSignoIn))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        //Constantes
        double centimetros = 30.48;
        double metros = 0.3048;
        double pulgadas = 12;
        
        double metricaCentimetros;
        double metricaMetros;
        double metricaPulgadas;
        
        lblSignoCm.setEnabled(true);
        lblSignoIn.setEnabled(true);
        lblSignoMts.setEnabled(true);

        try {
            if (txtInputPies.getText().length()>0) {
                DecimalFormat decimales = new DecimalFormat("#.##");
                metricaCentimetros = Double.parseDouble(txtInputPies.getText())*centimetros;
                metricaMetros = Double.parseDouble(txtInputPies.getText())*metros;
                metricaPulgadas = Double.parseDouble(txtInputPies.getText())*pulgadas;

                lblCm.setText(decimales.format(metricaCentimetros));
                lblMts.setText(decimales.format(metricaMetros));
                lblIn.setText(decimales.format(metricaPulgadas));
            }else{
                lblCm.setText("Numero error");
                lblMts.setText("Numero error");
                lblIn.setText("Numero error");
            }

        } catch (Exception e) {
            lblCm.setText("Ingrese un número");
            lblMts.setText("Ingrese un número");
            lblIn.setText("Ingrese un número");
            System.out.println("Hubo un error "+e);
        }   
        
    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblMts;
    private javax.swing.JLabel lblSignoCm;
    private javax.swing.JLabel lblSignoFt;
    private javax.swing.JLabel lblSignoIn;
    private javax.swing.JLabel lblSignoMts;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtInputPies;
    // End of variables declaration//GEN-END:variables
}
