/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alura.cl.conversor.view;

import java.text.DecimalFormat;

/**
 *
 * @author Nitro 5
 */
public class JpanelKiloBytes extends javax.swing.JPanel {

    /**
     * Creates new form JpanelPies
     */
    public JpanelKiloBytes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSigno = new javax.swing.JLabel();
        txtInputBytes = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        lblMb = new javax.swing.JLabel();
        lblGb = new javax.swing.JLabel();
        lblTb = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSignoMb = new javax.swing.JLabel();
        lblSignoGb = new javax.swing.JLabel();
        lblSignoTb = new javax.swing.JLabel();

        lblSigno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSigno.setText("Bytes");

        txtInputBytes.setText(" ");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        lblMb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMb.setText(" ");

        lblGb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGb.setText(" ");

        lblTb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTb.setText(" ");

        lblTitulo.setText("Bytes a MB - GB -TB");

        lblSignoMb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoMb.setText("Mb");
        lblSignoMb.setEnabled(false);

        lblSignoGb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoGb.setText("Gb");
        lblSignoGb.setEnabled(false);

        lblSignoTb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSignoTb.setText("Tb");
        lblSignoTb.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSigno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoTb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoGb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignoMb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInputBytes, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConvertir))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputBytes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir)
                    .addComponent(lblSigno))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMb)
                    .addComponent(lblSignoMb))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGb)
                    .addComponent(lblSignoGb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTb)
                    .addComponent(lblSignoTb))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        //Constantes
        double mb = 0.001;
        double gb = 0.000001;
        double tb = 0.0000000001;
        
        double metricaMegabytes;
        double metricaGigabytes;
        double metricaTerabytes;
        
        lblSignoMb.setEnabled(true);
        lblSignoGb.setEnabled(true);
        lblSignoTb.setEnabled(true);

        try {
            if (txtInputBytes.getText().length()>0) {
                DecimalFormat decimales = new DecimalFormat("#.####");
                metricaMegabytes = Double.parseDouble(txtInputBytes.getText())*mb;
                metricaGigabytes = Double.parseDouble(txtInputBytes.getText())*gb;
                metricaTerabytes = Double.parseDouble(txtInputBytes.getText())*tb;

                lblMb.setText(decimales.format(metricaMegabytes));
                lblGb.setText(decimales.format(metricaGigabytes));
                lblTb.setText(decimales.format(metricaTerabytes));
            }else{
                lblMb.setText("Numero error");
                lblGb.setText("Numero error");
                lblTb.setText("Numero error");
            }

        } catch (Exception e) {
            lblMb.setText("Ingrese un número");
            lblGb.setText("Ingrese un número");
            lblTb.setText("Ingrese un número");
            System.out.println("Hubo un error "+e);
        }   
        
    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel lblGb;
    private javax.swing.JLabel lblMb;
    private javax.swing.JLabel lblSigno;
    private javax.swing.JLabel lblSignoGb;
    private javax.swing.JLabel lblSignoMb;
    private javax.swing.JLabel lblSignoTb;
    private javax.swing.JLabel lblTb;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtInputBytes;
    // End of variables declaration//GEN-END:variables
}
