/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alura.cl.conversor.view;

import java.awt.BorderLayout;

/**
 *
 * @author Nitro 5
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEuro = new javax.swing.JButton();
        BtnOtros = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnDolar = new javax.swing.JButton();
        BtnArgentino = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnEuro.setText("Euro");
        BtnEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEuroActionPerformed(evt);
            }
        });

        BtnOtros.setText("Otros");
        BtnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOtrosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecciona una opción");

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel2)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        BtnDolar.setText("Dolar");
        BtnDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDolarActionPerformed(evt);
            }
        });

        BtnArgentino.setText("Argentino");
        BtnArgentino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnArgentinoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CONVERSOR DE MONEDA Y OTROS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(BtnDolar)
                .addGap(18, 18, 18)
                .addComponent(BtnEuro)
                .addGap(18, 18, 18)
                .addComponent(BtnArgentino)
                .addGap(18, 18, 18)
                .addComponent(BtnOtros)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnArgentino, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDolarActionPerformed
       
        
        if ("Dolar".equals(BtnDolar.getText())) {
            JpanelDolar dolar = new JpanelDolar();        
            dolar.setSize(300, 300);
            dolar.setLocation(30, 50);

            Content.removeAll();
            Content.add(dolar, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
            
            
        }else{
            JpanelGramos gramos = new JpanelGramos();        
            gramos.setSize(300, 300);
            gramos.setLocation(30, 50);

            Content.removeAll();
            Content.add(gramos, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
        }
    }//GEN-LAST:event_BtnDolarActionPerformed

    private void BtnEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEuroActionPerformed
        
        
        if ("Euro".equals(BtnEuro.getText())) {
            JpanelEuro euro = new JpanelEuro();        
            euro.setSize(300, 300);
            euro.setLocation(30, 50);

            Content.removeAll();
            Content.add(euro, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
            
            
        }else{
            JpanelPies pies = new JpanelPies();        
            pies.setSize(300, 300);
            pies.setLocation(30, 50);

            Content.removeAll();
            Content.add(pies, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
        }
    }//GEN-LAST:event_BtnEuroActionPerformed

    private void BtnArgentinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnArgentinoActionPerformed
               
        if ("Argentino".equals(BtnArgentino.getText())) {
            JpanelPesoChe pesoChe = new JpanelPesoChe();        
            pesoChe.setSize(300, 300);
            pesoChe.setLocation(30, 50);

            Content.removeAll();
            Content.add(pesoChe, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
            
            
        }else{
            JpanelKiloBytes pulgadas = new JpanelKiloBytes();        
            pulgadas.setSize(300, 300);
            pulgadas.setLocation(30, 50);

            Content.removeAll();
            Content.add(pulgadas, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
        }
    }//GEN-LAST:event_BtnArgentinoActionPerformed

    private void BtnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOtrosActionPerformed
       
        if ("Gramos".equals(BtnDolar.getText())) {
            BtnDolar.setText("Dolar");
            BtnEuro.setText("Euro");
            BtnArgentino.setText("Argentino");
            Content.removeAll();
            Content.revalidate();
            Content.repaint();
                System.out.println("Dentro del IF");
        } else{
            System.out.println("Dentro del ELSE");
            BtnDolar.setText("Gramos");
            BtnEuro.setText("Pies");
            BtnArgentino.setText("Pulgadas");
            Content.removeAll();
            Content.revalidate();
            Content.repaint();
        }
        
        
        
        
    }//GEN-LAST:event_BtnOtrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnArgentino;
    private javax.swing.JButton BtnDolar;
    private javax.swing.JButton BtnEuro;
    private javax.swing.JButton BtnOtros;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
